import { HeroSlide, AnnouncementItem, HomepageOffer, HomepageCard } from "@/types/homepage";

export const DEFAULT_HERO_SLIDES: HeroSlide[] = [
  {
    id: "hero-1",
    title: "Upgrade Your Everyday Tech",
    alt: "Upgrade Your Everyday Tech - Original products, top brands",
    desktopImage: "/images/hero-banner-1.jpg",
    mobileImage: "/images/hero-banner-1.jpg",
    redirectType: "shop",
    redirectValue: "",
    order: 1,
    isEnabled: true,
  },
  {
    id: "hero-2",
    title: "Upgrade Your World With Smart Tech",
    alt: "Upgrade Your World With Smart Technology - Latest laptops and electronics",
    desktopImage: "/images/hero-banner-2.jpg",
    mobileImage: "/images/hero-banner-2.jpg",
    redirectType: "category",
    redirectValue: "laptops",
    order: 2,
    isEnabled: true,
  },
  {
    id: "hero-3",
    title: "Welcome Offer 10% Off Accessories",
    alt: "Welcome offer 10% off on accessories - Headphones, cases and wearables",
    desktopImage: "/images/hero-banner-3.jpg",
    mobileImage: "/images/hero-banner-3.jpg",
    redirectType: "category",
    redirectValue: "accessories",
    order: 3,
    isEnabled: true,
  },
  {
    id: "hero-4",
    title: "Next Level Performance & Power",
    alt: "Next Level Performance - Experience power, speed, and innovation",
    desktopImage: "/images/hero-banner-4.jpg",
    mobileImage: "/images/hero-banner-4.jpg",
    redirectType: "category",
    redirectValue: "smartphones",
    order: 4,
    isEnabled: true,
  },
];

export const DEFAULT_ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: "ann-1",
    text: "EXCLUSIVE LAUNCH OFFER: BUY ANY FLAGSHIP DEVICE, GET 50% OFF ACCESSORIES",
    link: "/shop?isDeal=true",
    order: 1,
    isEnabled: true,
  },
  {
    id: "ann-2",
    text: "FREE JBL FLIP 6 SPEAKER BUNDLE WITH APEX SMARTPHONE PRO",
    link: "/shop",
    order: 2,
    isEnabled: true,
  },
  {
    id: "ann-3",
    text: "INSURED EXPRESS COURIER SHIPPING ON ORDERS OVER $99",
    link: "/shop",
    order: 3,
    isEnabled: true,
  },
  {
    id: "ann-4",
    text: "COMPLIMENTARY 2-YEAR CONCIERGE WARRANTY ON ALL PRODUCTS",
    link: "/shop",
    order: 4,
    isEnabled: true,
  },
  {
    id: "ann-5",
    text: "0% INTEREST EMI PLANS AVAILABLE ON ALL LAPTOPS & PHONES",
    link: "/shop",
    order: 5,
    isEnabled: true,
  },
];

export const DEFAULT_OFFERS: HomepageOffer[] = [
  {
    id: "offer-1",
    title: "Festival Hardware Gala",
    tagline: "Flat 15% Off Flagship Smartphones & Laptops",
    badge: "Limited Offer",
    code: "FESTIVE15",
    discountType: "percent",
    discountAmount: 15,
    ctaHref: "/shop?isDeal=true",
    isEnabled: true,
    order: 1,
  },
  {
    id: "offer-2",
    title: "10% Instant Bank Cashback",
    tagline: "Applicable on All Major Credit & Debit Cards",
    badge: "Bank Special",
    code: "BANK10",
    discountType: "percent",
    discountAmount: 10,
    ctaHref: "/shop",
    isEnabled: true,
    order: 2,
  },
  {
    id: "offer-3",
    title: "First Order Welcome Discount",
    tagline: "$50 Flat Discount on Your First Hardware Purchase",
    badge: "New Customer",
    code: "WELCOME50",
    discountType: "fixed",
    discountAmount: 50,
    ctaHref: "/shop",
    isEnabled: true,
    order: 3,
  },
  {
    id: "offer-4",
    title: "No-Cost 24-Month EMI",
    tagline: "0% Interest & 0 Down Payment Options",
    badge: "Easy Ownership",
    code: "ZEROEMI",
    discountType: "percent",
    discountAmount: 0,
    ctaHref: "/shop",
    isEnabled: true,
    order: 4,
  },
];

export const DEFAULT_CARDS: HomepageCard[] = [
  // 1. Our Products Category Slider Cards
  {
    id: "card-cat-1",
    section: "category_slider",
    slotName: "Smartphones",
    title: "Titanium Smartphones",
    subtitle: "Apex Flagship Series",
    badge: "Smartphones",
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=800&auto=format&fit=crop",
    categorySlug: "smart-phones",
    ctaHref: "/shop?category=smart-phones",
    order: 1,
    isEnabled: true,
  },
  {
    id: "card-cat-2",
    section: "category_slider",
    slotName: "Audio & Acoustics",
    title: "Studio Acoustics",
    subtitle: "Headphones & Earphones",
    badge: "Audio",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop",
    categorySlug: "headphones-earphones",
    ctaHref: "/shop?category=headphones-earphones",
    order: 2,
    isEnabled: true,
  },
  {
    id: "card-cat-3",
    section: "category_slider",
    slotName: "Power & Charging",
    title: "Power & Charging",
    subtitle: "Fast Powerbanks & Adapters",
    badge: "Powerbanks",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=800&auto=format&fit=crop",
    categorySlug: "powerbanks",
    ctaHref: "/shop?category=powerbanks",
    order: 3,
    isEnabled: true,
  },
  {
    id: "card-cat-4",
    section: "category_slider",
    slotName: "Mobile Accessories",
    title: "Mobile Accessories",
    subtitle: "Cases, Protectors & Mounts",
    badge: "Accessories",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800&auto=format&fit=crop",
    categorySlug: "mobile-accessories",
    ctaHref: "/shop?category=mobile-accessories",
    order: 4,
    isEnabled: true,
  },
  {
    id: "card-cat-5",
    section: "category_slider",
    slotName: "Apps & Softwares",
    title: "Apps & Softwares",
    subtitle: "Productivity & Utilities",
    badge: "Software",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    categorySlug: "apps-softwares",
    ctaHref: "/shop?category=apps-softwares",
    order: 5,
    isEnabled: true,
  },
  {
    id: "card-cat-6",
    section: "category_slider",
    slotName: "Tablets",
    title: "Tablets & E-Readers",
    subtitle: "High Definition Displays",
    badge: "Tablets",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800&auto=format&fit=crop",
    categorySlug: "tablets",
    ctaHref: "/shop?category=tablets",
    order: 6,
    isEnabled: true,
  },
  {
    id: "card-cat-7",
    section: "category_slider",
    slotName: "Laptops",
    title: "HyperBook Laptops",
    subtitle: "M4 Max Compute",
    badge: "Laptops",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800&auto=format&fit=crop",
    categorySlug: "laptops",
    ctaHref: "/shop?category=laptops",
    order: 7,
    isEnabled: false,
  },
  {
    id: "card-cat-8",
    section: "category_slider",
    slotName: "Smart Home",
    title: "Smart Home Automation",
    subtitle: "Thread & Matter IoT",
    badge: "Smart Home",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=800&auto=format&fit=crop",
    categorySlug: "home-theatres",
    ctaHref: "/shop?category=home-theatres",
    order: 8,
    isEnabled: false,
  },

  // 2. Bento Promo & Special Deal Cards (4 Cards)
  {
    id: "card-bento-1",
    section: "bento",
    slotName: "Bento Top-Left Promo Banner",
    title: "GET UP TO 50% OFF",
    subtitle: "Exclusive Weekend Hardware Deals",
    badge: "50% Off",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop",
    ctaText: "Get Discount",
    ctaHref: "/shop?category=audio",
    order: 9,
    isEnabled: true,
  },
  {
    id: "card-bento-2",
    section: "bento",
    slotName: "Bento Weekend Special Card",
    title: "Weekend Special",
    subtitle: "Keep it sleek with Titanium Pro",
    badge: "Weekend Special",
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=800&auto=format&fit=crop",
    ctaText: "Explore",
    ctaHref: "/products/flagship-smartphone-pro",
    order: 10,
    isEnabled: true,
  },
  {
    id: "card-bento-3",
    section: "bento",
    slotName: "Bento Bottom-Left Promo Card",
    title: "AeroBuds Studio",
    subtitle: "Studio Sound Architecture",
    badge: "Limited Edition",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=600&auto=format&fit=crop",
    ctaText: "Avail Offers",
    ctaHref: "/shop",
    order: 11,
    isEnabled: true,
  },
  {
    id: "card-bento-picks",
    section: "bento",
    slotName: "Our Picks",
    title: "Our Picks Product",
    subtitle: "Live selected product from WooCommerce",
    badge: "Our Picks",
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=600&auto=format&fit=crop",
    productSlug: "flagship-smartphone-pro",
    ctaHref: "/products/flagship-smartphone-pro",
    order: 12,
    isEnabled: true,
  },
  {
    id: "card-bento-bestseller",
    section: "bento",
    slotName: "Best Seller",
    title: "Best Seller Product",
    subtitle: "Live selected product from WooCommerce",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=600&auto=format&fit=crop",
    productSlug: "aerobuds-max",
    ctaHref: "/products/aerobuds-max",
    order: 13,
    isEnabled: true,
  },
  {
    id: "card-bento-4",
    section: "bento",
    slotName: "Bento Bottom-Right Innovation Banner",
    title: "Bring Bold Innovation",
    subtitle: "3nm Neural Engine & Studio Optics",
    badge: "Innovation",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop",
    ctaText: "Explore Optics",
    ctaHref: "/shop?category=optics",
    order: 14,
    isEnabled: true,
  },
];
